const meetingObject = {
    agenda: 'Meeting',
    default_password: false,
    duration: 60,
    password: '',
    pre_schedule: false,
    recurrence: {
        type: 1,
    },
    schedule_for: '',
    settings: {
        additional_data_center_regions: [],
        allow_multiple_devices: true,
        alternative_hosts: '',
        alternative_hosts_email_notification: true,
        approval_type: 1,
        approved_or_denied_countries_or_regions: {},
        audio: 'voip',
        audio_conference_info: 'test',
        authentication_domains: '',
        authentication_exception: [],
        authentication_option: '',
        auto_recording: '',
        breakout_room: {
            enable: false,
            rooms: [],
        },
        calendar_type: 1,
        close_registration: false,
        contact_email: '',
        contact_name: '',
        email_notification: false,
        encryption_type: 'enhanced_encryption',
        focus_mode: false,
        global_dial_in_countries: [],
        host_video: false,
        jbh_time: 0,
        join_before_host: true,
        language_interpretation: {
            enable: false,
            interpreters: [],
        },
        sign_language_interpretation: {
            enable: false,
            interpreters: [],
        },
        meeting_authentication: true,
        meeting_invitees: [],
        mute_upon_entry: false,
        participant_video: false,
        private_meeting: false,
        registrants_confirmation_email: false,
        registrants_email_notification: false,
        registration_type: 1,
        show_share_button: true,
        use_pmi: false,
        waiting_room: false,
        watermark: false,
        host_save_video_order: false,
        alternative_host_update_polls: false,
        internal_meeting: false,
        continuous_meeting_chat: {
            enable: true,
            auto_add_invited_external_users: true,
        },
        participant_focused_meeting: false,
        push_change_to_calendar: false,
        resources: [],
    },
    start_time: '',
    template_id: '',
    timezone: '',
    topic: 'My Meeting',
    tracking_fields: [],
    type: 2,
}

export default meetingObject
